---

- hosts: ec2-instance

  become: true

  tasks:

    - name: install python3

      apt: name=python3 update_cache=yes state=latest



    - name: install python

      apt: name=python update_cache=yes state=latest



    - name: install java

      apt: name=openjdk-8-jre-headless update_cache=yes state=latest


    - name: install java2

      apt: name=openjdk-8-jdk update_cache=yes state=latest



    - name: install jenkins apt repository key

      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present



    - name: configure the repository

      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present



    - name: install jenkins

      apt: name=jenkins update_cache=yes state=latest



    - name: ensure jenkins service is running

      service: name=jenkins state=started


    - name: install maven

      apt: name=maven update_cache=yes state=latest

    - name: install docker

      apt: name=docker.io update_cache=yes state=latest

    - name: add jenkins user to docker group
      ansible.builtin.user:
              name: jenkins
              groups: docker
              append: yes

    - name: generate open ssh key pair
      community.crypto.openssh_keypair:
              path: /home/ubuntu/.ssh/jenkins_agent_key
              force: True

    - name: change permission for docker.sock
      ansible.builtin.file:
              path: /var/run/docker.sock
              mode: '0666'
    - name: run the comamnd prereq for agent container
      command: "sudo setfacl --modify user::rw /var/run/docker.sock"

    - name: install python-docker
      apt: name=python-docker  update_cache=yes state=latest

    - name: pull image from dockerhub
      command: "docker pull tinakamali/agent-jenkins"

    - name: copy file to ec2 to build the image
      ansible.builtin.copy:
              src: ./dockerrun.sh
              dest: /home/ubuntu/.ssh/dockerrun.sh

    - name: change permission of dockerrun.sh
      ansible.builtin.file:
              path: /home/ubuntu/.ssh/dockerrun.sh
              mode: ugo+x

    - name: run the dockerrun.sh
      command: "./dockerrun.sh"
      args:
              chdir: /home/ubuntu/.ssh

