---
- hosts: ec2-instance

  become: true

  tasks:

    - name: add wheel group
      group:
              name: wheel
              state: present

    - name: add users
      user: name={{ item }}  group=users groups=wheel
      with_items:
              - tinakaa
              - ubuntu
              - jenkins

    - name: allow wheel group to have passwordless sudo
      lineinfile:
              dest: /etc/sudoers
              state: present
              regexp: '^%wheel'
              line: '%wheel ALL=(ALL) NOPASSWD:ALL'


 
